name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest

    name: Node

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2

      - name: Install Node dependencies
        run: yarn --frozen-lockfile

      - name: Build
        run: yarn build

      - name: Build Sample
        run: yarn build:sample

      - name: Build Storybook
        run: yarn build:storybook

      - name: Lint
        run: yarn lint
