name: Pages

on:
  push:
    branches:
      - main

jobs:
  pages:
    runs-on: ubuntu-latest

    name: Publish GitHub Pages

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: latest
      - name: Install Node dependencies
        run: yarn --frozen-lockfile
      - name: Build the storybook
        run: yarn build:storybook
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.5.0
        with:
          branch: gh-pages
          folder: packages/storybook/_gh-pages
