name: Pages

on:
  push:
    branches:
      - main
    tags:

jobs:
  pages:
    runs-on: ubuntu-latest

    name: Publish GitHub Pages

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: Install Node dependencies
        run: yarn --frozen-lockfile
      - name: Build the storybook
        run: yarn build:storybook
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: gh-pages
          folder: packages/storybook/_gh-pages
